/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualizacao;

import Controlador.Classificar;

/**
 *
 * @author PMF
 */
public class ClassificarMenu extends javax.swing.JFrame {

    /**
     * Creates new form ClassificarMenu
     */
    public ClassificarMenu() {
        classificacao = new Classificar();
        initComponents();
        buttonGroup1.add(j0Radio);
        buttonGroup1.add(j1Radio);
        buttonGroup1.add(j2Radio);
        buttonGroup1.add(j3Radio);
        buttonGroup1.add(j4Radio);
        buttonGroup1.add(j5Radio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        j0Radio = new javax.swing.JRadioButton();
        j1Radio = new javax.swing.JRadioButton();
        j2Radio = new javax.swing.JRadioButton();
        j3Radio = new javax.swing.JRadioButton();
        j4Radio = new javax.swing.JRadioButton();
        j5Radio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j0Radio.setText("0");
        j0Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j0RadioActionPerformed(evt);
            }
        });

        j1Radio.setText("1");
        j1Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1RadioActionPerformed(evt);
            }
        });

        j2Radio.setText("2");
        j2Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2RadioActionPerformed(evt);
            }
        });

        j3Radio.setText("3");
        j3Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3RadioActionPerformed(evt);
            }
        });

        j4Radio.setText("4");
        j4Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4RadioActionPerformed(evt);
            }
        });

        j5Radio.setText("5");
        j5Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5RadioActionPerformed(evt);
            }
        });

        jLabel1.setText("Classifique o serviço");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(j0Radio)
                        .addGap(18, 18, 18)
                        .addComponent(j1Radio)
                        .addGap(18, 18, 18)
                        .addComponent(j2Radio)
                        .addGap(18, 18, 18)
                        .addComponent(j3Radio)
                        .addGap(18, 18, 18)
                        .addComponent(j4Radio)
                        .addGap(18, 18, 18)
                        .addComponent(j5Radio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j0Radio)
                    .addComponent(j1Radio)
                    .addComponent(j2Radio)
                    .addComponent(j3Radio)
                    .addComponent(j4Radio)
                    .addComponent(j5Radio))
                .addGap(87, 87, 87)
                .addComponent(okButton)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (nenhumaSelecao()) 
            Mensagem.mostrarJanela("Selecione uma opção");
        else {
            classificacao.atualiazarNota();
            this.dispose();
            new OpcoesMenu().setVisible(true);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void j0RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j0RadioActionPerformed
        classificacao.setNovaNota(0);
    }//GEN-LAST:event_j0RadioActionPerformed

    private void j1RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1RadioActionPerformed
        classificacao.setNovaNota(1);
    }//GEN-LAST:event_j1RadioActionPerformed

    private void j2RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2RadioActionPerformed
        classificacao.setNovaNota(2);
    }//GEN-LAST:event_j2RadioActionPerformed

    private void j3RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3RadioActionPerformed
        classificacao.setNovaNota(3);
    }//GEN-LAST:event_j3RadioActionPerformed

    private void j4RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4RadioActionPerformed
        classificacao.setNovaNota(4);
    }//GEN-LAST:event_j4RadioActionPerformed

    private void j5RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5RadioActionPerformed
        classificacao.setNovaNota(5);
    }//GEN-LAST:event_j5RadioActionPerformed

    private boolean nenhumaSelecao() {
       return !(j0Radio.isSelected() || j1Radio.isSelected() ||
               j2Radio.isSelected() || j3Radio.isSelected() ||
               j4Radio.isSelected() || j5Radio.isSelected());
    }
    
    private final Classificar classificacao;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton j0Radio;
    private javax.swing.JRadioButton j1Radio;
    private javax.swing.JRadioButton j2Radio;
    private javax.swing.JRadioButton j3Radio;
    private javax.swing.JRadioButton j4Radio;
    private javax.swing.JRadioButton j5Radio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
